name: Cypress Tests

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  cypress-run:
    runs-on: windows-latest  # Specify Windows as the operating system

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js and Install Cypress
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - run: npm install cypress@latest --save-dev

      - run: npm install

      - run: npm test
